### ISSUE TITLE
Le résumé de la donnée ne s'affiche pas dans une petite zone de la fiche

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/plugin-arcgis-pro#30]
Merci de préciser dans votre rapport :

## Environnement :

- Version du logiciel ArcGis Pro : 2.5.1
- Version du plugin Isogeo ArcGis Pro : 0.7.2
- Architecture du processeur : 64 bits
- Version du système Windows (Windows 10, Windows Server 2019, ...) : Windows Server 2019
- Autres informations potentiellement utiles : 

## Reproduire
* Se connecter au partage plugin ArcGIS Pro dev & test
* Afficher les résultats de la recherche
* Survoler la liste de donnée et maintenir le curseur sur une donnée

plugin-arcgis-pro-dev-tests

## Comportement constaté
Quand on survole une donnée dans la liste, le résumé ne s'affiche pas.

## Comportement souhaité
Comportement décrit dans la partie [consulter le résumé](http://help.isogeo.com/arcmap/fr/usage/metadata.html#abstract)

## Informations supplémentaires
  
**Je vous remercie pour votre contribution =D**

**Comment by SimonSAMPERE** [comment]
En fait il s'agirait de faire en sorte que toutes la ligne de résultat soit concerné par le tooltip qui permet d'afficher le résumé de la fiche. Mais du coup c'est pas prévu pour l'instant

**Comment by leodarengosse** [comment]
ça fonctionne bien en positionnant le curseur sur la zone du titre. Je pense que c'est suffisant donc on peut clore ce ticket
