### ISSUE TITLE
[Feature] Ajouter un message explicite lorsuqe l'ajout via la connexion SDE est impossible

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/plugin-arcgis-pro#38]
## Environnement :

- ArcGis Pro 2.5
- Isogeo ArcGis Pro 0.8
- Processeur 64 bits
- Windows Server 2019

## Reproduire
- Ouvrir le plugin
- Vérifier qu'aucun fichier de connexion SDE n'est paramétré dans les paramètres
- Effectuer une recherche en sélectionnant le format Esri Geodatabase SDE
- Ajouter une couche arcsde

## Comportement constaté
- Le message "la métadonnée" n'a pas été correctement renseignée" s'affiche.

## Comportement souhaité
- Un message indiquant à l'utilisateur qu'il n'a pas paramétré de connexion SDE dans les paramètres serait plus pertinent.
- Si la connexion est bien paramétrée mais que la donnée n'est pas accessible via ce fichier de connexion, l'indiquer également à l'utilisateur dans un message du style "La donnée X n'est pas disponible via la connexion Y.sde"

**Comment by Mouzzi-C** [comment]
* Ça fonctionne bien lorsque le fichier de connexion est mal configuré
![image](https://user-images.githubusercontent.com/63340073/123068505-3e05cf00-d412-11eb-9820-6a89c20ffc42.png)

* Message actuel lorsque le mauvais fichier sde est configuré : 
![image](https://user-images.githubusercontent.com/63340073/123064848-ee71d400-d40e-11eb-98c7-b5caea471aae.png)
