### ISSUE TITLE
Gestion du markdown dans l'affichage de la fiche de métadonnées

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/plugin-arcgis-pro#41]
## Reproduire
1. Sélectionner une fiche de métadonnée
2. Vérifier si le Markdown apparait

## Comportement constaté
Le markdown apparaît quand on visualise les fiches dans le plugin

## Comportement souhaité
Le Markdown devait être pris en compte
## Capture d'écran

![image](https://github.com/isogeo/plugin-arcgis-pro/assets/16936198/f31c0e1a-2acb-4c45-acae-ba9cb622af12)

![image](https://github.com/isogeo/plugin-arcgis-pro/assets/16936198/9abf41b2-d934-42f9-9f47-233f968e4061)

**Comment by SimonSAMPERE** [comment]
Avant chiffrage il faudrait lister les champs pour lesquels il faut gérer le markdown (résumé, contexte de collecte...)

Actuellement ça n'est pas gérer non plus dans le plugin QGIS

**Comment by leodarengosse** [comment]
Je propose donc de clore ce ticket
