### ISSUE TITLE
[BUG] Impossible d'ajouter des données ArcSDE à la carte

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/plugin-arcgis-pro#67]
## Environnement :

- Version du logiciel ArcGis Pro 2.7.1
- Version du plugin Isogeo ArcGis Pro 1.0.1
- Architecture du processeur : 64 bits
- Version du système Windows : Windows Server 2019

## Reproduire
1. Insérer une nouvelle carte
2. Ouvrir ArcGIS Pro sur Mojito
3. S'assurer que le partage associé est celui d'Isogeo Demo 2.0
4. Filtrer le propriétaire sur Isogeo Demo 2.0
5. Filtrer le type de ressource Vecteur
6. Ajouter la donnée ArcSDE "Pistes cyclables temporaires mises en place pendant le déconfinement - Ville de Paris"

## Comportement constaté
Une erreur s'affiche lorsqu'on essaye d'ajouter la donnée à la carte. (l'ajout à la carte sans passer par le plugin fonctionne)
![image](https://user-images.githubusercontent.com/63340073/110491257-641c9300-80f1-11eb-9602-e333981bacab.png)

## Comportement souhaité
Possibilité d'ajouté une donnée arcsde à la carte à partir du plugin arcgis pro

**Comment by jgrosmaire** [comment]
Cause du problème remontée par Carlo : Problème de détection de format depuis le scan
