### ISSUE TITLE
[BUG] Impossible d'ajouter une donnée sde à la carte

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/plugin-arcgis-pro#78]
Merci de préciser dans votre rapport :

## Environnement :

- Version du logiciel ArcGis Pro 2.8 (je n'ai pas plus de précision sur la version du client)
- Version du plugin Isogeo ArcGis Pro : 01.0.3
- Architecture du processeur : 64 bits
- Version du système Windows : Windows Server 2016
- Autres informations potentiellement utiles : Voici les logs du plugin que le client m'a envoyé : 
[Isogeo_log.txt](https://github.com/isogeo/plugin-arcgis-pro/files/8070250/Isogeo_log.txt)

## Reproduire
* Paramétrer le fichier de connexion sde 
* rechercher la donnée sde souhaitée
* cliquer sur "+" pour ajouter la donnée à la carte

**Je n'ai pas réussi à reproduire ce comportement sur ma machine**

## Comportement constaté chez deux clients uniquement
Lorsque l'on ajoute une donnée sde à la carte, aucune donnée et aucun message d'erreur ne s'affichent. 

## Comportement souhaité
Pouvoir ajouter la donnée sde à la carte

**Comment by Mouzzi-C** [comment]
les logs actuels montrent que la donnée à bien été ajoutée à la carte 
[Isogeo_pbplugin_log.txt](https://github.com/isogeo/plugin-arcgis-pro/files/8123165/Isogeo_pbplugin_log.txt)

**Comment by emmanuelamicel** [comment]
Pour traiter le ticket, j'ai ajouté des logs supplémentaires au fichier `Isogeo.Map/MapFunctions/MapFunctions.cs`. Les logs affichent quel type de couche est ajouté à la carte, quel URL de service est testé. Ce bug particulier est sûrement lié à la méthode `AddLayer(serviceType)`, qui dans les trois cas où la méthode se finissait, affichait "END - Add Layer". J'ai modifié les logs selon si la méthode se conclut par l'ajout d'une couche, l'erreur FileNotFound ou une erreur différente.

**Comment by SimonSAMPERE** [comment]
Pas reproductible
