### ISSUE TITLE
Adaptation du plugin à l'environnement On Premises

### ISSUE THREAD

**Issue by jgrosmaire** [isogeo/plugin-arcgis-pro#79]
## Tâches

Il est nécessaire de pouvoir configurer l'URL des requêtes à l'API Isogeo. 
Pour l'instant, les plugins seront compilés spécifiquement pour chaque client.

**Comment by emmanuelamicel** [comment]
Pour chaque nouveau client, pour l'instant : ouvrir le plugin ArcGIS Pro dans Visual Studio, modifier `AddIn/App.config` et remplacer les variables `<apiIdUrl>` et `<apiUrl>` et le tour est joué.

En testant en local avec une API branchée à la base de données de QA, le plugin a fonctionné.

**Comment by SimonSAMPERE** [comment]
@emmanuelamicel reste-t-il des chose à faire sur ce ticket avant de le fermer ?

**Comment by emmanuelamicel** [comment]
L'idéal serait de recetter en testant avec l'environnement de recette d'une manière ou d'une autre, mais dans l'ensemble je vois pas ce qui pourrait bloquer. Le problème c'est d'avoir une licence ArcGIS Pro avec l'environnement de recette, mais on peut toujours tenter quelque chose avec une API installée en local et configurée comme en On Premises (certificats et DNS installés).

**Comment by SimonSAMPERE** [comment]
@emmanuelamicel 
J'ai essayé le plugin ArcGIS pro branché à l'API on premises de recette (que tu m'as envoyé le 02/02/2023) sur la VM WindowsQGisRecette (infos de connexion dans le Keepass Dev). j'ai réussi à l'installer, au lancement, il me demande les infos d'authentification à l'API, je lui fourni bien ceux de l'appli que j'avais créée dans le manage de recette juste avant et l'authentification échoue :
![image](https://user-images.githubusercontent.com/41120579/216600606-82160fff-0e8d-4520-acc9-ec1edb54312e.png)

J'avais bien configuré un partage vers cette application.

Lorsque je testais le même fichier de connexion avec le plugin QGIS sur la même machine, ça fonctionnait mais QGIS levait un warning indiquant que le certificat n'était pas reconnu. En ignorant ce warning l'authentification pouvait se faire.

J'ai donc ajouté au magasin de certificats de la machine le certificat de la CA qui signe le certificat de l'API.

Après avoir fait ça, plus de warning dans QGIS et l'authentification du plugin ArcGIS pro a fonctionné !

Cela veut donc dire qu'il est nécessaire d'ajouter le certificat de la CA qui signe les certificats de l'API au magasin de certificats des machines sur lesquelles on souhaite utiliser le plugin ArcGIS Pro (du coup @LyesIsogeo et @jgrosmaire c'est bien bloquant pour le plugin ArcGIS Pro mais pas pour le plugin QGIS)

Je l'avais déjà ajouté à la doc donc on est good : 
![image](https://user-images.githubusercontent.com/41120579/216602677-a2245fb8-8e20-4921-acb5-1f09b7d2ded7.png)

**Comment by SimonSAMPERE** [comment]
la suite dans #91
