### ISSUE TITLE
Compatibilité avec la version 3.0 d'ArcGIS Pro

### ISSUE THREAD

**Issue by emmanuelamicel** [isogeo/plugin-arcgis-pro#82]
## Comportement constaté

Après avoir mis à jour mon plugin ArcGIS en version 3.0, il n'est plus possible de build le projet dans Visual Studio.

## Investigation

Une version compilée avec ArcGIS 2.8 ne fonctionnera pas avec la nouvelle version du plugin. De même, de nombreux messages d'erreur apparaissent dans la console de Visual Studio lorsque qu'on tente de compiler le plugin avec une version 3.0 installée.

![image](https://user-images.githubusercontent.com/64600355/203278657-487769f8-f1f5-4438-8921-d237af45c3ce.png)

Un [guide de migration](https://github.com/Esri/arcgis-pro-sdk/wiki/ProConcepts-3.0-Migration-Guide) a été rédigé par Esri, et une extension a été créée dans Visual Studio.

**Comment by leodarengosse** [comment]
La version 2.0 beta-1 a été installée sur Mojito avec ArcGIS Pro 3.0. La recette peut-être lancée

**Comment by Mouzzi-C** [comment]
Ajouter le fichier d’installation dans le dossier produit (vérifier si la version est la bonne. sinon envoyer un mail à Vianney)

**Comment by Mouzzi-C** [comment]
Je viens de vérifier, on a la version 2.0.0beta3. @VianneyDoleans est-ce que tu pourras nous envoyer le fichier d'installation de la 2.0.0, stp ?

**Comment by VianneyDoleans** [comment]
@Mouzzi-C  Je peux générer une version 2.0.0 depuis mon pc, mais je ne peux cependant pas signer l'exécutable avec une clé Isogeo si jamais vous le faisiez.

**Comment by leodarengosse** [comment]
On le faisait pas donc pas de problème
