### ISSUE TITLE
Générer les esriAddinX pour la PPP et l'EGI

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/plugin-arcgis-pro#84]
Dès qu'on aura connaissance des URLs de l'API à la PPP et à l'EGI, on pourra packager leurs plugin ArcGIS Pro.

**Comment by Mouzzi-C** [comment]
J'ai envoyé un mail à la cliente. Je vous tiens au courant dès que j'ai les urls

**Comment by emmanuelamicel** [comment]
Pour la PPP :

https://id-api.isogeo.pp.minint.fr/
https://v1-api.isogeo.pp.minint.fr/
https://services-api.isogeo.pp.minint.fr/
