### ISSUE TITLE
Recette PAGP 2.0.0-beta2 sur AGP 3.0 (toujours en cours)

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/plugin-arcgis-pro#87]
Version comparées : 2.0.0-beta2 avec la 1.0.3

- [x] paramétrage du fichier de connexion : ok
- [x] ajout dela donnée à la carte avec sde, EMS, EFS : ok  pour tout
- [x] ajout à la carte de WFS et WMS --> non fonctionnel sur les deux versions
- [ ] affichage de la fiche de métadonnées
  - [ ] les évènements ne sont pas récupérés sur la version 2.0.0-beta2
![image](https://github.com/isogeo/plugin-arcgis-pro/assets/63340073/093f7ee9-2bfd-4e27-a80b-8544a473cfd3)

  - [x] le reste des informations sont ok
- [ ] modification du client_secret : enregistrement réalisé mais ce sont les fiches de l'ancien client_secret paramétré qui s'affichent --> il faut redémarrer arcgis pro 3.0 pour que la modification soit prise en compte
- [ ] sauvegarde d'une recherche : la suavegarde n'est pas réalisée. impossible de modifier le nom de la sauvegarde et de la sélectionner dans les recherche rapides
étapes à suivre : 
1. Sélection des filtres format et type de ressources
2. dans l'onglet paramètres>paramètres de recherche>enregistrer>renommer

- [x] lancer la dernière recherche en recherche rapide 

Guide de recette : https://docs.google.com/spreadsheets/d/1NVfVXIJNysdC9zEwVIRh0G3sOze1xXIBanT1AcBcGkk/edit?pli=1#gid=0

**Comment by Mouzzi-C** [comment]
recette avec la dernière version prennant en compte les retours de recette ci-dessus.

- [x] paramétrage du fichier de connexion 
- [x] ajout dela donnée à la carte avec sde, EMS, EFS : ok  pour tout
- [x] affichage de la fiche de métadonnées
- [x] modification du client_secret 
- [x] sauvegarde d'une recherche  
- [x] lancer la dernière recherche en recherche rapide 
- [x] recherche textuelle
- [x] utilisation des différents filtres

C'est bon pour moi. Merci @VianneyDoleans 

@leodarengosse t'auras pas besoin de faire de recette finalement.

**Comment by leodarengosse** [comment]
Super ! merci @Mouzzi-C et @VianneyDoleans

**Comment by leodarengosse** [comment]
Déposer dans le dossier des extensions
