### ISSUE TITLE
[BUG- Westmount] Erreur lors de l'installation du plugin

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/plugin-arcgis-pro#93]
Merci de préciser dans votre rapport :

## Environnement :

- Version du logiciel ArcGis Pro 3.0.3
- Version du plugin Isogeo ArcGis Pro 2.0
- Architecture du processeur : 64 bits
- Version du système Windows (Windows 10, Windows Server 2019, ...) : Windows 10
- Autres informations potentiellement utiles : pas d'autre info

## Reproduire
- Expliquez les étapes pour réaliser le bug

1. installation du plugin
2. lancement d'AGP
3. lancement du plugin

--> une erreur : `Error configuration : missing or wrong App.config file`

id : plugin-arcgis-pro-ville-de-west-de7ab105caaa471fa6ddb2464d66786e
secret : 818XdfS7hxNuEqWh7QCVbB006nCNrtr0ZTvnRcar44E6FO61CmOZtiAUaSZwZcbb

## Comportement constaté
impossible d'accéder au plugin et l'erreur ci-dessus s'affiche

## Capture d'écran

![image](https://github.com/isogeo/plugin-arcgis-pro/assets/63340073/b57a3808-cf21-4c11-88f3-b41aff37bee5)

**Comment by leodarengosse** [comment]
Même erreur à ADP avec ArcGIS Pro 3.1.2

**Comment by leodarengosse** [comment]
@SimonSAMPERE a testé sur son poste avec ArcGIS Pro 3.1 et obtient la même erreur

**Comment by VianneyDoleans** [comment]
Bonjour,

Est-ce que les postes sur lesquels le plugin v2 a été installé ayant un souci avaient déjà reçu le plugin v1 avec ArcGis Pro 1.X ?

A chaud après avoir lu le ticket, ma supposition serait un problème de compatibilité avec la v1 après la montée de version.
Est-ce que le problème est apparu sur des postes n'ayant jamais utilisé le plugin ArcGis Pro ?
Si la réponse est bien non, je tenterai de : désinstaller le plugin puis déplacer/renommer le dossier Document/Isogeo (contenant /ArcGisPro/ArcGisPro.json, c'est la sauvegarde), déplacer/renommer le dossier \Users\[User]\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{d3cd9cd7-2008-4a27-be55-da1aeb26239f}\ puis réinstaller le plugin.

L'erreur de la screenshot apparait lors de la phase de loading de la configuration du plugin. Le plugin va regarder s'il existe un fichier de config existant sur la machine (Document/IsogeoArcGisPro/ArcGisPro.json) et dans le cas contraire le créer en utilisant le fichier de référence contenu à l'emplacement du plugin (\Users\[User]\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{d3cd9cd7-2008-4a27-be55-da1aeb26239f}\) obtenu en installant le plugin. 

Si le fichier json est incompatible/corrmpu ou/et le fichier de référence n'est pas accessible, le plugin ne charge pas.

**Comment by SimonSAMPERE** [comment]
Salut @VianneyDoleans , on a pu reproduire le bug sur mon poste : 
* j'avais mis à jour ArcGIS Pro depuis 2.8 vers 3.1 avant d'installer le plugin
* le plugin n'y avait jamais été installé avant

Pour info, dans mon répertoire `C:\Users\SimonSAMPERE\AppData\Local\ESRI\ArcGISPro`, je n'ai pas de dossier `\AssemblyCache{d3cd9cd7-2008-4a27-be55-da1aeb26239f}`

**Comment by VianneyDoleans** [comment]
J'ai trouvé le souci. 
Durant la phase de migration du projet pour ArcGisPro de 2.5 vers 3.0, le ficher app.config qui est le fichier de référence que j'ai mentionné dans mon message précédent n'a pas été inclus pour la compilation. Si cela fonctionne sur mon PC ainsi que le poste utilisé pour les tests, c'est par ce que nous avions déjà le fichier json dans Documents\Isogeo\ArcGisPro, donc le plugin n'est pas allé chercher le fichier app.config pour générer ce json.

j'ai send la version 2.0.1 avec cet ajout de l'include du fichier par mail.

A priori le ticket peut être clos, je vous laisse regarder.

**Comment by SimonSAMPERE** [comment]
@VianneyDoleans je confirme que ça fonctionne sur mon poste, bien joué 🦾 

Je pense qu'on fermera le ticket quand @Mouzzi-C testé cette nouvelle version 2.0.1 chez le client

**Comment by Mouzzi-C** [comment]
j'ai eu un retour de la vville Westmount, le plugin a fonctionné. Bien joué les amis !

je ferme le ticket
